# Generated by Django 5.2.5 on 2025-11-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_rename_lat_pokemonentity_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
