# Generated by Django 5.2.5 on 2025-11-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_alter_pokemonentity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
